[package]
name = "read_keypair_file"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
tokio = {version = "1.35.0", features = ["full"] }
shellexpand = "3.1.0"
solana-sdk = "1.16.23"
util = { path = "../../lib/util" }