[package]
name = "token_list_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
anchor-client = "0.29.0"
anchor-spl = "0.29.0"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
shellexpand = "3.1.0"
spl-token = "4.0.0"
tokio = { version = "1.35.0", features = ["full"] }
util = { path = "../../lib/util" }
