[package]
name = "pyth_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
solana-client = "1.16.23"
pyth-sdk-solana = "0.9.0"
tokio = { version = "1.35.0", features = ["full"] }
util = { path = "../../lib/util" }